### ISSUE TITLE
Error loading custom_components.xiaomi_miio.climate in HA 0.89

### ISSUE THREAD

**Issue by aktifin** [syssi/xiaomi_airconditioningcompanion#49]
When I update HA to 0.89 and put the latest climate.py and __init__.py into xiaomi_miio folder ,
xiaomi_miio dosen't worked and display the error like this
Error loading custom_components.xiaomi_miio_climate.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miio/climate.py", line 14, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'SUPPORT_ON_OFF' from 'homeassistant.components.climate' (/usr/src/app/homeassistant/components/climate/__init__.py)

**Comment by zz66** [comment]
Same issue, HA 0.89 + python 3.7.
ERROR (MainThread) [homeassistant.config] Package climate setup failed. Component climate cannot be merged. Expected a dict.

**Comment by syssi** [comment]
It looks like the component isn't compatible right now. I will fix it ASAP.

**Comment by befantasy** [comment]
It seems that it remains conflict with the official component - [Xiaomi Mi Robot Vacuum.](https://www.home-assistant.io/components/vacuum.xiaomi_miio/) even if update to your latest release.

**Comment by syssi** [comment]
Could you post the error messages / exceptions? It fear you have to cooy all the other xiaomi_miio files to the same folder at custom_components

**Comment by befantasy** [comment]
**when I put the xiaomi_miio folder to customer_components,  Xiaomi Mi Robot Vacuum can't be used any more** 


2019-03-07 17:08:50 INFO (MainThread) [homeassistant.loader] Loaded xiaomi_miio from custom_components.xiaomi_miio
2019-03-07 17:08:50 WARNING (MainThread) [homeassistant.loader] You are using a custom component for xiaomi_miio which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-03-07 17:08:50 INFO (MainThread) [homeassistant.loader] Loaded xiaomi_miio.climate from custom_components.xiaomi_miio.climate
2019-03-07 17:08:50 WARNING (MainThread) [homeassistant.loader] You are using a custom component for xiaomi_miio.climate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-03-07 17:08:50 INFO (MainThread) [homeassistant.setup] Setting up climate
2019-03-07 17:08:50 INFO (MainThread) [homeassistant.loader] Loaded switch.command_line from homeassistant.components.switch.command_line
2019-03-07 17:08:50 INFO (MainThread) [homeassistant.loader] Loaded wake_on_lan from homeassistant.components.wake_on_lan
2019-03-07 17:08:50 INFO (MainThread) [homeassistant.loader] Loaded switch.wake_on_lan from homeassistant.components.switch.wake_on_lan
2019-03-07 17:08:50 INFO (MainThread) [homeassistant.setup] Setting up homekit
2019-03-07 17:08:50 INFO (MainThread) [homeassistant.loader] Loaded sensor.command_line from homeassistant.components.sensor.command_line
2019-03-07 17:08:50 INFO (MainThread) [homeassistant.loader] Loaded sensor.template from homeassistant.components.sensor.template
2019-03-07 17:08:50 INFO (MainThread) [homeassistant.setup] Setting up sensor
2019-03-07 17:08:50 ERROR (MainThread) [homeassistant.loader] Unable to find platform xiaomi_miio. Search path was limited to path of component: custom_components

**Comment by syssi** [comment]
I've renamed the component now. Please update the component and your configuration.yaml.

**Comment by befantasy** [comment]
Thanks a lot !!!
You responded too fast.
